apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: springcommunity/spring-petclinic-discovery-server

        ports:
        - containerPort: 8761

        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server:8888

        resources:
          limits:
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30

        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
