apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
  namespace: petclinic

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana-server

  template:
    metadata:
      labels:
        app: grafana-server

    spec:
      containers:
      - name: grafana-server
        image: grafana/grafana:latest

        ports:
        - containerPort: 3000

        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin

        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin123

        resources:
          limits:
            memory: "256Mi"
